#pragma once
#include <cstdint>

// 描画系で使う固定色ブラシの ID。CommandExecutor は brushes_[BrushId::*] を
// O(1) で配列ルックアップする。動的色のみ Custom を指定し brush_pool 経由になる。
enum class BrushId : uint8_t {
    Text,
    Heading,
    CodeBg,
    CodeText,
    Link,
    Hr,
    BlockquoteBar,
    BlockquoteText,
    Selection,
    TableStripe,
    SyntaxKeyword,
    SyntaxType,
    SyntaxString,
    SyntaxNumber,
    SyntaxComment,
    SyntaxPreprocessor,
    SyntaxFunction,
    AlertNote,
    AlertTip,
    AlertImportant,
    AlertWarning,
    AlertCaution,
    TitleBarBg,
    TitleBarText,
    TitleBarButtonHover,
    TitleBarButtonActive,
    TitleBarCloseRed,
    TitleBarCloseWhite,
    PaneBg,
    Splitter,
    PaneItemHover,
    PaneItemActive,
    ScrollbarThumb,
    OverlayWhite,
    OverlayBlack,
    OverlayGestureBg,
    GestureTrail,
    SearchBarBg,
    SearchBarBorder,
    SearchInputBg,
    SearchInputText,
    SearchHighlight,
    SearchHighlightCurrent,
    SearchNoMatchBg,
    Count,
    // 動的色を意味するセンチネル。brush_pool 経由でブラシを解決する。
    Custom = 0xFF,
};
