// 各言語のキーワード・型名テーブル。syntax.cpp からのみ include される内部ヘッダ。
// 長さバケット + 各バケット内ソート済み配列。
// 識別子検索時は word.size() で対応バケットへ直接ジャンプし、典型 1〜10 件の小バケットを
// 二分探索する。長さ違いのキーワードと wmemcmp する無駄を排除する。
// MakeBucketed は consteval なのでバケット境界はコンパイル時に確定する。
#pragma once
#include "doc_text.h"
#include <algorithm>
#include <array>
#include <span>
#include <string_view>
#include <tuple>
#include <cstdint>

namespace syntax_keywords {

using namespace std::literals;

// バケット最大長。全テーブルで現状最長 23 (`ConstructorParameters`) なので余裕を持たせて 32。
inline constexpr size_t KEYWORD_MAX_LEN = 32;

// type-erased view。LANGUAGE_DEFS で言語ごとに異なる N を 1 つの配列に格納するため、
// 各 BucketedTable<N> から暗黙変換できる軽量ビューを使う。
struct KeywordTable {
    std::span<const std::string_view> entries;
    std::span<const uint16_t> bucket_offsets; // size = KEYWORD_MAX_LEN + 2

    [[nodiscard]] constexpr bool empty() const noexcept
    {
        return entries.empty();
    }

    [[nodiscard]] constexpr bool contains(std::string_view word) const noexcept
    {
        if (entries.empty()) {
            return false;
        }
        const size_t len = word.size();
        if (len == 0 || len + 1 >= bucket_offsets.size()) {
            return false;
        }
        const size_t start = bucket_offsets[len];
        const size_t end = bucket_offsets[len + 1];
        if (start == end) {
            return false;
        }
        return std::ranges::binary_search(entries.subspan(start, end - start), word);
    }
};

template <size_t N>
struct BucketedTable {
    std::array<std::string_view, N> entries{};
    std::array<uint16_t, KEYWORD_MAX_LEN + 2> bucket_offsets{};

    constexpr operator KeywordTable() const noexcept
    {
        return KeywordTable{
            std::span<const std::string_view>{ entries },
            std::span<const uint16_t>{ bucket_offsets }
        };
    }
};

template <size_t N>
consteval BucketedTable<N> MakeBucketed(std::array<std::string_view, N> arr)
{
    // (length, lex) 辞書順でソート。同じ長さ内では二分探索のために lex 昇順を維持する。
    std::ranges::sort(arr, [](std::string_view a, std::string_view b) {
        if (a.size() != b.size()) {
            return a.size() < b.size();
        }
        return a < b;
    });

    BucketedTable<N> r;
    r.entries = arr;

    // 各長さの個数をカウント、prefix-sum で開始位置に変換。
    for (const auto& s : arr) {
        if (s.size() <= KEYWORD_MAX_LEN) {
            r.bucket_offsets[s.size() + 1]++;
        }
    }
    for (size_t i = 1; i < r.bucket_offsets.size(); i++) {
        r.bucket_offsets[i] = static_cast<uint16_t>(r.bucket_offsets[i] + r.bucket_offsets[i - 1]);
    }
    return r;
}

inline constexpr auto CPP_KEYWORDS = MakeBucketed(std::to_array<std::string_view>({
    "auto",
    "break",
    "case",
    "catch",
    "class",
    "co_await",
    "co_return",
    "co_yield",
    "concept",
    "const",
    "const_cast",
    "consteval",
    "constexpr",
    "constinit",
    "continue",
    "decltype",
    "default",
    "delete",
    "do",
    "dynamic_cast",
    "else",
    "enum",
    "explicit",
    "export",
    "extern",
    "false",
    "final",
    "for",
    "friend",
    "goto",
    "if",
    "import",
    "inline",
    "module",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "nullptr",
    "operator",
    "override",
    "private",
    "protected",
    "public",
    "register",
    "reinterpret_cast",
    "requires",
    "return",
    "sizeof",
    "static",
    "static_assert",
    "static_cast",
    "struct",
    "switch",
    "template",
    "this",
    "throw",
    "true",
    "try",
    "typedef",
    "typeid",
    "typename",
    "union",
    "using",
    "virtual",
    "void",
    "volatile",
    "while",
}));

inline constexpr auto CPP_TYPES = MakeBucketed(std::to_array<std::string_view>({
    "BOOL",
    "DWORD",
    "HANDLE",
    "HINSTANCE",
    "HRESULT",
    "HWND",
    "LPARAM",
    "LRESULT",
    "POINT",
    "RECT",
    "SIZE",
    "UINT",
    "WPARAM",
    "array",
    "bool",
    "char",
    "char16_t",
    "char32_t",
    "char8_t",
    "double",
    "float",
    "int",
    "int16_t",
    "int32_t",
    "int64_t",
    "int8_t",
    "long",
    "map",
    "optional",
    "pair",
    "ptrdiff_t",
    "set",
    "shared_ptr",
    "short",
    "signed",
    "size_t",
    "span",
    "string",
    "string_view",
    "tuple",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "uint8_t",
    "unique_ptr",
    "unordered_map",
    "unordered_set",
    "unsigned",
    "variant",
    "vector",
    "wchar_t",
    "weak_ptr",
    "wstring",
    "wstring_view",
}));

inline constexpr auto PYTHON_KEYWORDS = MakeBucketed(std::to_array<std::string_view>({
    "False",
    "None",
    "True",
    "and",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "class",
    "continue",
    "def",
    "del",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "from",
    "global",
    "if",
    "import",
    "in",
    "is",
    "lambda",
    "nonlocal",
    "not",
    "or",
    "pass",
    "raise",
    "return",
    "try",
    "while",
    "with",
    "yield",
}));

inline constexpr auto PYTHON_TYPES = MakeBucketed(std::to_array<std::string_view>({
    "Exception",
    "IOError",
    "IndexError",
    "KeyError",
    "OSError",
    "RuntimeError",
    "StopIteration",
    "TypeError",
    "ValueError",
    "bool",
    "bytearray",
    "bytes",
    "classmethod",
    "complex",
    "dict",
    "float",
    "frozenset",
    "int",
    "list",
    "memoryview",
    "object",
    "property",
    "range",
    "set",
    "staticmethod",
    "str",
    "tuple",
    "type",
}));

inline constexpr auto JS_KEYWORDS = MakeBucketed(std::to_array<std::string_view>({
    "as",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "export",
    "extends",
    "finally",
    "for",
    "from",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "let",
    "new",
    "of",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
}));

inline constexpr auto JS_TYPES = MakeBucketed(std::to_array<std::string_view>({
    "Array",
    "BigInt",
    "Boolean",
    "Date",
    "Error",
    "Function",
    "Infinity",
    "JSON",
    "Map",
    "Math",
    "NaN",
    "Number",
    "Object",
    "Promise",
    "Proxy",
    "Reflect",
    "RegExp",
    "Set",
    "String",
    "Symbol",
    "WeakMap",
    "WeakSet",
    "console",
    "document",
    "false",
    "globalThis",
    "null",
    "true",
    "undefined",
    "window",
}));

inline constexpr auto GO_KEYWORDS = MakeBucketed(std::to_array<std::string_view>({
    "break",
    "case",
    "chan",
    "const",
    "continue",
    "default",
    "defer",
    "else",
    "fallthrough",
    "for",
    "func",
    "go",
    "goto",
    "if",
    "import",
    "interface",
    "map",
    "package",
    "range",
    "return",
    "select",
    "struct",
    "switch",
    "type",
    "var",
}));

inline constexpr auto GO_TYPES = MakeBucketed(std::to_array<std::string_view>({
    "any",
    "bool",
    "byte",
    "comparable",
    "complex128",
    "complex64",
    "error",
    "false",
    "float32",
    "float64",
    "int",
    "int16",
    "int32",
    "int64",
    "int8",
    "iota",
    "nil",
    "rune",
    "string",
    "true",
    "uint",
    "uint16",
    "uint32",
    "uint64",
    "uint8",
    "uintptr",
}));

inline constexpr auto RUST_KEYWORDS = MakeBucketed(std::to_array<std::string_view>({
    "Self",
    "as",
    "async",
    "await",
    "break",
    "const",
    "continue",
    "crate",
    "dyn",
    "else",
    "enum",
    "extern",
    "false",
    "fn",
    "for",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "macro_rules",
    "match",
    "mod",
    "move",
    "mut",
    "pub",
    "ref",
    "return",
    "self",
    "static",
    "struct",
    "super",
    "trait",
    "true",
    "type",
    "unsafe",
    "use",
    "where",
    "while",
    "yield",
}));

inline constexpr auto RUST_TYPES = MakeBucketed(std::to_array<std::string_view>({
    "Arc",
    "BTreeMap",
    "BTreeSet",
    "Box",
    "Cell",
    "Cow",
    "Err",
    "HashMap",
    "HashSet",
    "LinkedList",
    "None",
    "Ok",
    "Option",
    "PhantomData",
    "Pin",
    "Rc",
    "RefCell",
    "Result",
    "Some",
    "String",
    "Vec",
    "VecDeque",
    "bool",
    "char",
    "f32",
    "f64",
    "i128",
    "i16",
    "i32",
    "i64",
    "i8",
    "isize",
    "str",
    "u128",
    "u16",
    "u32",
    "u64",
    "u8",
    "usize",
}));

// TypeScript = JS + TS固有キーワード（マージ済み）
inline constexpr auto TS_KEYWORDS = MakeBucketed(std::to_array<std::string_view>({
    "abstract",
    "as",
    "asserts",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "declare",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "finally",
    "for",
    "from",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "infer",
    "instanceof",
    "interface",
    "is",
    "keyof",
    "let",
    "module",
    "namespace",
    "new",
    "of",
    "override",
    "readonly",
    "return",
    "satisfies",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "try",
    "type",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
}));

inline constexpr auto TS_TYPES = MakeBucketed(std::to_array<std::string_view>({
    "Array",
    "Awaited",
    "BigInt",
    "Boolean",
    "Capitalize",
    "ConstructorParameters",
    "Date",
    "Error",
    "Exclude",
    "Extract",
    "Function",
    "Infinity",
    "InstanceType",
    "JSON",
    "Lowercase",
    "Map",
    "Math",
    "NaN",
    "NonNullable",
    "Number",
    "Object",
    "Omit",
    "Parameters",
    "Partial",
    "Pick",
    "Promise",
    "Proxy",
    "Readonly",
    "Record",
    "Reflect",
    "RegExp",
    "Required",
    "ReturnType",
    "Set",
    "String",
    "Symbol",
    "ThisType",
    "Uncapitalize",
    "Uppercase",
    "WeakMap",
    "WeakSet",
    "any",
    "bigint",
    "boolean",
    "console",
    "document",
    "false",
    "globalThis",
    "never",
    "null",
    "number",
    "object",
    "string",
    "symbol",
    "true",
    "undefined",
    "unknown",
    "window",
}));

inline constexpr auto BASH_KEYWORDS = MakeBucketed(std::to_array<std::string_view>({
    "break",
    "case",
    "continue",
    "declare",
    "do",
    "done",
    "elif",
    "else",
    "esac",
    "eval",
    "exec",
    "exit",
    "export",
    "fi",
    "for",
    "function",
    "if",
    "in",
    "local",
    "readonly",
    "return",
    "select",
    "set",
    "shift",
    "source",
    "then",
    "time",
    "trap",
    "typeset",
    "unset",
    "until",
    "while",
}));

inline constexpr auto BASH_TYPES = MakeBucketed(std::to_array<std::string_view>({
    "alias",
    "builtin",
    "cd",
    "command",
    "echo",
    "false",
    "getopts",
    "let",
    "mapfile",
    "printf",
    "pwd",
    "read",
    "readarray",
    "test",
    "true",
    "type",
    "unalias",
    "which",
}));

// PowerShell（大文字小文字を区別しないマッチングのためキーワードは小文字で格納）
inline constexpr auto PWSH_KEYWORDS = MakeBucketed(std::to_array<std::string_view>({
    "begin",
    "break",
    "catch",
    "class",
    "continue",
    "data",
    "do",
    "dynamicparam",
    "else",
    "elseif",
    "end",
    "enum",
    "exit",
    "filter",
    "finally",
    "for",
    "foreach",
    "from",
    "function",
    "hidden",
    "if",
    "in",
    "inlinescript",
    "param",
    "process",
    "return",
    "static",
    "switch",
    "throw",
    "trap",
    "try",
    "until",
    "using",
    "while",
    "workflow",
}));

inline constexpr auto PWSH_TYPES = MakeBucketed(std::to_array<std::string_view>({
    "array",
    "bool",
    "byte",
    "char",
    "datetime",
    "decimal",
    "double",
    "false",
    "float",
    "hashtable",
    "int",
    "long",
    "null",
    "regex",
    "scriptblock",
    "string",
    "timespan",
    "true",
    "void",
    "xml",
}));

// Cmd（大文字小文字を区別しないマッチングのためキーワードは小文字で格納）
inline constexpr auto CMD_KEYWORDS = MakeBucketed(std::to_array<std::string_view>({
    "call",
    "defined",
    "do",
    "echo",
    "else",
    "endlocal",
    "equ",
    "errorlevel",
    "exist",
    "exit",
    "for",
    "geq",
    "goto",
    "gtr",
    "if",
    "in",
    "leq",
    "lss",
    "neq",
    "not",
    "off",
    "on",
    "pause",
    "rem",
    "set",
    "setlocal",
}));

inline constexpr auto CMD_TYPES = MakeBucketed(std::to_array<std::string_view>({
    "attrib",
    "cls",
    "color",
    "copy",
    "del",
    "dir",
    "find",
    "findstr",
    "ipconfig",
    "md",
    "mkdir",
    "more",
    "move",
    "net",
    "netsh",
    "ping",
    "rd",
    "reg",
    "ren",
    "rename",
    "rmdir",
    "robocopy",
    "sc",
    "sort",
    "start",
    "taskkill",
    "tasklist",
    "title",
    "type",
    "ver",
    "xcopy",
}));

// JSON / JSONC: リテラル値のみ。型名は該当概念がない。
inline constexpr auto JSON_KEYWORDS = MakeBucketed(std::to_array<std::string_view>({
    "false",
    "null",
    "true",
}));

} // namespace syntax_keywords
