// 各言語のキーワード・型名テーブル。syntax.cpp からのみ include される内部ヘッダ。
// 長さバケット + 各バケット内ソート済み配列。
// 識別子検索時は word.size() で対応バケットへ直接ジャンプし、典型 1〜10 件の小バケットを
// 二分探索する。長さ違いのキーワードと wmemcmp する無駄を排除する。
// MakeBucketed は consteval なのでバケット境界はコンパイル時に確定する。
#pragma once
#include "doc_text.h"
#include <algorithm>
#include <array>
#include <span>
#include <string_view>
#include <tuple>
#include <cstdint>

namespace syntax_keywords {

using namespace std::literals;

// バケット最大長。全テーブルで現状最長 23 (`ConstructorParameters`) なので余裕を持たせて 32。
inline constexpr size_t KEYWORD_MAX_LEN = 32;

// type-erased view。LANGUAGE_DEFS で言語ごとに異なる N を 1 つの配列に格納するため、
// 各 BucketedTable<N> から暗黙変換できる軽量ビューを使う。
struct KeywordTable {
    std::span<const mendo::doc_string_view> entries;
    std::span<const uint16_t> bucket_offsets; // size = KEYWORD_MAX_LEN + 2

    [[nodiscard]] constexpr bool empty() const noexcept
    {
        return entries.empty();
    }

    [[nodiscard]] constexpr bool contains(mendo::doc_string_view word) const noexcept
    {
        if (entries.empty()) {
            return false;
        }
        const size_t len = word.size();
        if (len == 0 || len + 1 >= bucket_offsets.size()) {
            return false;
        }
        const size_t start = bucket_offsets[len];
        const size_t end = bucket_offsets[len + 1];
        if (start == end) {
            return false;
        }
        return std::ranges::binary_search(entries.subspan(start, end - start), word);
    }
};

template <size_t N>
struct BucketedTable {
    std::array<mendo::doc_string_view, N> entries{};
    std::array<uint16_t, KEYWORD_MAX_LEN + 2> bucket_offsets{};

    constexpr operator KeywordTable() const noexcept
    {
        return KeywordTable{
            std::span<const mendo::doc_string_view>{ entries },
            std::span<const uint16_t>{ bucket_offsets }
        };
    }
};

template <size_t N>
consteval BucketedTable<N> MakeBucketed(std::array<mendo::doc_string_view, N> arr)
{
    // (length, lex) 辞書順でソート。同じ長さ内では二分探索のために lex 昇順を維持する。
    std::ranges::sort(arr, [](mendo::doc_string_view a, mendo::doc_string_view b) {
        if (a.size() != b.size()) {
            return a.size() < b.size();
        }
        return a < b;
    });

    BucketedTable<N> r;
    r.entries = arr;

    // 各長さの個数をカウント、prefix-sum で開始位置に変換。
    for (const auto& s : arr) {
        if (s.size() <= KEYWORD_MAX_LEN) {
            r.bucket_offsets[s.size() + 1]++;
        }
    }
    for (size_t i = 1; i < r.bucket_offsets.size(); i++) {
        r.bucket_offsets[i] = static_cast<uint16_t>(r.bucket_offsets[i] + r.bucket_offsets[i - 1]);
    }
    return r;
}

inline constexpr auto CPP_KEYWORDS = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("auto"),
    MENDO_LIT("break"),
    MENDO_LIT("case"),
    MENDO_LIT("catch"),
    MENDO_LIT("class"),
    MENDO_LIT("co_await"),
    MENDO_LIT("co_return"),
    MENDO_LIT("co_yield"),
    MENDO_LIT("concept"),
    MENDO_LIT("const"),
    MENDO_LIT("const_cast"),
    MENDO_LIT("consteval"),
    MENDO_LIT("constexpr"),
    MENDO_LIT("constinit"),
    MENDO_LIT("continue"),
    MENDO_LIT("decltype"),
    MENDO_LIT("default"),
    MENDO_LIT("delete"),
    MENDO_LIT("do"),
    MENDO_LIT("dynamic_cast"),
    MENDO_LIT("else"),
    MENDO_LIT("enum"),
    MENDO_LIT("explicit"),
    MENDO_LIT("export"),
    MENDO_LIT("extern"),
    MENDO_LIT("false"),
    MENDO_LIT("final"),
    MENDO_LIT("for"),
    MENDO_LIT("friend"),
    MENDO_LIT("goto"),
    MENDO_LIT("if"),
    MENDO_LIT("import"),
    MENDO_LIT("inline"),
    MENDO_LIT("module"),
    MENDO_LIT("mutable"),
    MENDO_LIT("namespace"),
    MENDO_LIT("new"),
    MENDO_LIT("noexcept"),
    MENDO_LIT("nullptr"),
    MENDO_LIT("operator"),
    MENDO_LIT("override"),
    MENDO_LIT("private"),
    MENDO_LIT("protected"),
    MENDO_LIT("public"),
    MENDO_LIT("register"),
    MENDO_LIT("reinterpret_cast"),
    MENDO_LIT("requires"),
    MENDO_LIT("return"),
    MENDO_LIT("sizeof"),
    MENDO_LIT("static"),
    MENDO_LIT("static_assert"),
    MENDO_LIT("static_cast"),
    MENDO_LIT("struct"),
    MENDO_LIT("switch"),
    MENDO_LIT("template"),
    MENDO_LIT("this"),
    MENDO_LIT("throw"),
    MENDO_LIT("true"),
    MENDO_LIT("try"),
    MENDO_LIT("typedef"),
    MENDO_LIT("typeid"),
    MENDO_LIT("typename"),
    MENDO_LIT("union"),
    MENDO_LIT("using"),
    MENDO_LIT("virtual"),
    MENDO_LIT("void"),
    MENDO_LIT("volatile"),
    MENDO_LIT("while"),
}));

inline constexpr auto CPP_TYPES = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("BOOL"),
    MENDO_LIT("DWORD"),
    MENDO_LIT("HANDLE"),
    MENDO_LIT("HINSTANCE"),
    MENDO_LIT("HRESULT"),
    MENDO_LIT("HWND"),
    MENDO_LIT("LPARAM"),
    MENDO_LIT("LRESULT"),
    MENDO_LIT("POINT"),
    MENDO_LIT("RECT"),
    MENDO_LIT("SIZE"),
    MENDO_LIT("UINT"),
    MENDO_LIT("WPARAM"),
    MENDO_LIT("array"),
    MENDO_LIT("bool"),
    MENDO_LIT("char"),
    MENDO_LIT("char16_t"),
    MENDO_LIT("char32_t"),
    MENDO_LIT("char8_t"),
    MENDO_LIT("double"),
    MENDO_LIT("float"),
    MENDO_LIT("int"),
    MENDO_LIT("int16_t"),
    MENDO_LIT("int32_t"),
    MENDO_LIT("int64_t"),
    MENDO_LIT("int8_t"),
    MENDO_LIT("long"),
    MENDO_LIT("map"),
    MENDO_LIT("optional"),
    MENDO_LIT("pair"),
    MENDO_LIT("ptrdiff_t"),
    MENDO_LIT("set"),
    MENDO_LIT("shared_ptr"),
    MENDO_LIT("short"),
    MENDO_LIT("signed"),
    MENDO_LIT("size_t"),
    MENDO_LIT("span"),
    MENDO_LIT("string"),
    MENDO_LIT("string_view"),
    MENDO_LIT("tuple"),
    MENDO_LIT("uint16_t"),
    MENDO_LIT("uint32_t"),
    MENDO_LIT("uint64_t"),
    MENDO_LIT("uint8_t"),
    MENDO_LIT("unique_ptr"),
    MENDO_LIT("unordered_map"),
    MENDO_LIT("unordered_set"),
    MENDO_LIT("unsigned"),
    MENDO_LIT("variant"),
    MENDO_LIT("vector"),
    MENDO_LIT("wchar_t"),
    MENDO_LIT("weak_ptr"),
    MENDO_LIT("wstring"),
    MENDO_LIT("wstring_view"),
}));

inline constexpr auto PYTHON_KEYWORDS = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("False"),
    MENDO_LIT("None"),
    MENDO_LIT("True"),
    MENDO_LIT("and"),
    MENDO_LIT("as"),
    MENDO_LIT("assert"),
    MENDO_LIT("async"),
    MENDO_LIT("await"),
    MENDO_LIT("break"),
    MENDO_LIT("class"),
    MENDO_LIT("continue"),
    MENDO_LIT("def"),
    MENDO_LIT("del"),
    MENDO_LIT("elif"),
    MENDO_LIT("else"),
    MENDO_LIT("except"),
    MENDO_LIT("finally"),
    MENDO_LIT("for"),
    MENDO_LIT("from"),
    MENDO_LIT("global"),
    MENDO_LIT("if"),
    MENDO_LIT("import"),
    MENDO_LIT("in"),
    MENDO_LIT("is"),
    MENDO_LIT("lambda"),
    MENDO_LIT("nonlocal"),
    MENDO_LIT("not"),
    MENDO_LIT("or"),
    MENDO_LIT("pass"),
    MENDO_LIT("raise"),
    MENDO_LIT("return"),
    MENDO_LIT("try"),
    MENDO_LIT("while"),
    MENDO_LIT("with"),
    MENDO_LIT("yield"),
}));

inline constexpr auto PYTHON_TYPES = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("Exception"),
    MENDO_LIT("IOError"),
    MENDO_LIT("IndexError"),
    MENDO_LIT("KeyError"),
    MENDO_LIT("OSError"),
    MENDO_LIT("RuntimeError"),
    MENDO_LIT("StopIteration"),
    MENDO_LIT("TypeError"),
    MENDO_LIT("ValueError"),
    MENDO_LIT("bool"),
    MENDO_LIT("bytearray"),
    MENDO_LIT("bytes"),
    MENDO_LIT("classmethod"),
    MENDO_LIT("complex"),
    MENDO_LIT("dict"),
    MENDO_LIT("float"),
    MENDO_LIT("frozenset"),
    MENDO_LIT("int"),
    MENDO_LIT("list"),
    MENDO_LIT("memoryview"),
    MENDO_LIT("object"),
    MENDO_LIT("property"),
    MENDO_LIT("range"),
    MENDO_LIT("set"),
    MENDO_LIT("staticmethod"),
    MENDO_LIT("str"),
    MENDO_LIT("tuple"),
    MENDO_LIT("type"),
}));

inline constexpr auto JS_KEYWORDS = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("as"),
    MENDO_LIT("async"),
    MENDO_LIT("await"),
    MENDO_LIT("break"),
    MENDO_LIT("case"),
    MENDO_LIT("catch"),
    MENDO_LIT("class"),
    MENDO_LIT("const"),
    MENDO_LIT("continue"),
    MENDO_LIT("debugger"),
    MENDO_LIT("default"),
    MENDO_LIT("delete"),
    MENDO_LIT("do"),
    MENDO_LIT("else"),
    MENDO_LIT("export"),
    MENDO_LIT("extends"),
    MENDO_LIT("finally"),
    MENDO_LIT("for"),
    MENDO_LIT("from"),
    MENDO_LIT("function"),
    MENDO_LIT("if"),
    MENDO_LIT("import"),
    MENDO_LIT("in"),
    MENDO_LIT("instanceof"),
    MENDO_LIT("let"),
    MENDO_LIT("new"),
    MENDO_LIT("of"),
    MENDO_LIT("return"),
    MENDO_LIT("static"),
    MENDO_LIT("super"),
    MENDO_LIT("switch"),
    MENDO_LIT("this"),
    MENDO_LIT("throw"),
    MENDO_LIT("try"),
    MENDO_LIT("typeof"),
    MENDO_LIT("var"),
    MENDO_LIT("void"),
    MENDO_LIT("while"),
    MENDO_LIT("with"),
    MENDO_LIT("yield"),
}));

inline constexpr auto JS_TYPES = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("Array"),
    MENDO_LIT("BigInt"),
    MENDO_LIT("Boolean"),
    MENDO_LIT("Date"),
    MENDO_LIT("Error"),
    MENDO_LIT("Function"),
    MENDO_LIT("Infinity"),
    MENDO_LIT("JSON"),
    MENDO_LIT("Map"),
    MENDO_LIT("Math"),
    MENDO_LIT("NaN"),
    MENDO_LIT("Number"),
    MENDO_LIT("Object"),
    MENDO_LIT("Promise"),
    MENDO_LIT("Proxy"),
    MENDO_LIT("Reflect"),
    MENDO_LIT("RegExp"),
    MENDO_LIT("Set"),
    MENDO_LIT("String"),
    MENDO_LIT("Symbol"),
    MENDO_LIT("WeakMap"),
    MENDO_LIT("WeakSet"),
    MENDO_LIT("console"),
    MENDO_LIT("document"),
    MENDO_LIT("false"),
    MENDO_LIT("globalThis"),
    MENDO_LIT("null"),
    MENDO_LIT("true"),
    MENDO_LIT("undefined"),
    MENDO_LIT("window"),
}));

inline constexpr auto GO_KEYWORDS = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("break"),
    MENDO_LIT("case"),
    MENDO_LIT("chan"),
    MENDO_LIT("const"),
    MENDO_LIT("continue"),
    MENDO_LIT("default"),
    MENDO_LIT("defer"),
    MENDO_LIT("else"),
    MENDO_LIT("fallthrough"),
    MENDO_LIT("for"),
    MENDO_LIT("func"),
    MENDO_LIT("go"),
    MENDO_LIT("goto"),
    MENDO_LIT("if"),
    MENDO_LIT("import"),
    MENDO_LIT("interface"),
    MENDO_LIT("map"),
    MENDO_LIT("package"),
    MENDO_LIT("range"),
    MENDO_LIT("return"),
    MENDO_LIT("select"),
    MENDO_LIT("struct"),
    MENDO_LIT("switch"),
    MENDO_LIT("type"),
    MENDO_LIT("var"),
}));

inline constexpr auto GO_TYPES = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("any"),
    MENDO_LIT("bool"),
    MENDO_LIT("byte"),
    MENDO_LIT("comparable"),
    MENDO_LIT("complex128"),
    MENDO_LIT("complex64"),
    MENDO_LIT("error"),
    MENDO_LIT("false"),
    MENDO_LIT("float32"),
    MENDO_LIT("float64"),
    MENDO_LIT("int"),
    MENDO_LIT("int16"),
    MENDO_LIT("int32"),
    MENDO_LIT("int64"),
    MENDO_LIT("int8"),
    MENDO_LIT("iota"),
    MENDO_LIT("nil"),
    MENDO_LIT("rune"),
    MENDO_LIT("string"),
    MENDO_LIT("true"),
    MENDO_LIT("uint"),
    MENDO_LIT("uint16"),
    MENDO_LIT("uint32"),
    MENDO_LIT("uint64"),
    MENDO_LIT("uint8"),
    MENDO_LIT("uintptr"),
}));

inline constexpr auto RUST_KEYWORDS = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("Self"),
    MENDO_LIT("as"),
    MENDO_LIT("async"),
    MENDO_LIT("await"),
    MENDO_LIT("break"),
    MENDO_LIT("const"),
    MENDO_LIT("continue"),
    MENDO_LIT("crate"),
    MENDO_LIT("dyn"),
    MENDO_LIT("else"),
    MENDO_LIT("enum"),
    MENDO_LIT("extern"),
    MENDO_LIT("false"),
    MENDO_LIT("fn"),
    MENDO_LIT("for"),
    MENDO_LIT("if"),
    MENDO_LIT("impl"),
    MENDO_LIT("in"),
    MENDO_LIT("let"),
    MENDO_LIT("loop"),
    MENDO_LIT("macro_rules"),
    MENDO_LIT("match"),
    MENDO_LIT("mod"),
    MENDO_LIT("move"),
    MENDO_LIT("mut"),
    MENDO_LIT("pub"),
    MENDO_LIT("ref"),
    MENDO_LIT("return"),
    MENDO_LIT("self"),
    MENDO_LIT("static"),
    MENDO_LIT("struct"),
    MENDO_LIT("super"),
    MENDO_LIT("trait"),
    MENDO_LIT("true"),
    MENDO_LIT("type"),
    MENDO_LIT("unsafe"),
    MENDO_LIT("use"),
    MENDO_LIT("where"),
    MENDO_LIT("while"),
    MENDO_LIT("yield"),
}));

inline constexpr auto RUST_TYPES = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("Arc"),
    MENDO_LIT("BTreeMap"),
    MENDO_LIT("BTreeSet"),
    MENDO_LIT("Box"),
    MENDO_LIT("Cell"),
    MENDO_LIT("Cow"),
    MENDO_LIT("Err"),
    MENDO_LIT("HashMap"),
    MENDO_LIT("HashSet"),
    MENDO_LIT("LinkedList"),
    MENDO_LIT("None"),
    MENDO_LIT("Ok"),
    MENDO_LIT("Option"),
    MENDO_LIT("PhantomData"),
    MENDO_LIT("Pin"),
    MENDO_LIT("Rc"),
    MENDO_LIT("RefCell"),
    MENDO_LIT("Result"),
    MENDO_LIT("Some"),
    MENDO_LIT("String"),
    MENDO_LIT("Vec"),
    MENDO_LIT("VecDeque"),
    MENDO_LIT("bool"),
    MENDO_LIT("char"),
    MENDO_LIT("f32"),
    MENDO_LIT("f64"),
    MENDO_LIT("i128"),
    MENDO_LIT("i16"),
    MENDO_LIT("i32"),
    MENDO_LIT("i64"),
    MENDO_LIT("i8"),
    MENDO_LIT("isize"),
    MENDO_LIT("str"),
    MENDO_LIT("u128"),
    MENDO_LIT("u16"),
    MENDO_LIT("u32"),
    MENDO_LIT("u64"),
    MENDO_LIT("u8"),
    MENDO_LIT("usize"),
}));

// TypeScript = JS + TS固有キーワード（マージ済み）
inline constexpr auto TS_KEYWORDS = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("abstract"),
    MENDO_LIT("as"),
    MENDO_LIT("asserts"),
    MENDO_LIT("async"),
    MENDO_LIT("await"),
    MENDO_LIT("break"),
    MENDO_LIT("case"),
    MENDO_LIT("catch"),
    MENDO_LIT("class"),
    MENDO_LIT("const"),
    MENDO_LIT("continue"),
    MENDO_LIT("debugger"),
    MENDO_LIT("declare"),
    MENDO_LIT("default"),
    MENDO_LIT("delete"),
    MENDO_LIT("do"),
    MENDO_LIT("else"),
    MENDO_LIT("enum"),
    MENDO_LIT("export"),
    MENDO_LIT("extends"),
    MENDO_LIT("finally"),
    MENDO_LIT("for"),
    MENDO_LIT("from"),
    MENDO_LIT("function"),
    MENDO_LIT("if"),
    MENDO_LIT("implements"),
    MENDO_LIT("import"),
    MENDO_LIT("in"),
    MENDO_LIT("infer"),
    MENDO_LIT("instanceof"),
    MENDO_LIT("interface"),
    MENDO_LIT("is"),
    MENDO_LIT("keyof"),
    MENDO_LIT("let"),
    MENDO_LIT("module"),
    MENDO_LIT("namespace"),
    MENDO_LIT("new"),
    MENDO_LIT("of"),
    MENDO_LIT("override"),
    MENDO_LIT("readonly"),
    MENDO_LIT("return"),
    MENDO_LIT("satisfies"),
    MENDO_LIT("static"),
    MENDO_LIT("super"),
    MENDO_LIT("switch"),
    MENDO_LIT("this"),
    MENDO_LIT("throw"),
    MENDO_LIT("try"),
    MENDO_LIT("type"),
    MENDO_LIT("typeof"),
    MENDO_LIT("var"),
    MENDO_LIT("void"),
    MENDO_LIT("while"),
    MENDO_LIT("with"),
    MENDO_LIT("yield"),
}));

inline constexpr auto TS_TYPES = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("Array"),
    MENDO_LIT("Awaited"),
    MENDO_LIT("BigInt"),
    MENDO_LIT("Boolean"),
    MENDO_LIT("Capitalize"),
    MENDO_LIT("ConstructorParameters"),
    MENDO_LIT("Date"),
    MENDO_LIT("Error"),
    MENDO_LIT("Exclude"),
    MENDO_LIT("Extract"),
    MENDO_LIT("Function"),
    MENDO_LIT("Infinity"),
    MENDO_LIT("InstanceType"),
    MENDO_LIT("JSON"),
    MENDO_LIT("Lowercase"),
    MENDO_LIT("Map"),
    MENDO_LIT("Math"),
    MENDO_LIT("NaN"),
    MENDO_LIT("NonNullable"),
    MENDO_LIT("Number"),
    MENDO_LIT("Object"),
    MENDO_LIT("Omit"),
    MENDO_LIT("Parameters"),
    MENDO_LIT("Partial"),
    MENDO_LIT("Pick"),
    MENDO_LIT("Promise"),
    MENDO_LIT("Proxy"),
    MENDO_LIT("Readonly"),
    MENDO_LIT("Record"),
    MENDO_LIT("Reflect"),
    MENDO_LIT("RegExp"),
    MENDO_LIT("Required"),
    MENDO_LIT("ReturnType"),
    MENDO_LIT("Set"),
    MENDO_LIT("String"),
    MENDO_LIT("Symbol"),
    MENDO_LIT("ThisType"),
    MENDO_LIT("Uncapitalize"),
    MENDO_LIT("Uppercase"),
    MENDO_LIT("WeakMap"),
    MENDO_LIT("WeakSet"),
    MENDO_LIT("any"),
    MENDO_LIT("bigint"),
    MENDO_LIT("boolean"),
    MENDO_LIT("console"),
    MENDO_LIT("document"),
    MENDO_LIT("false"),
    MENDO_LIT("globalThis"),
    MENDO_LIT("never"),
    MENDO_LIT("null"),
    MENDO_LIT("number"),
    MENDO_LIT("object"),
    MENDO_LIT("string"),
    MENDO_LIT("symbol"),
    MENDO_LIT("true"),
    MENDO_LIT("undefined"),
    MENDO_LIT("unknown"),
    MENDO_LIT("window"),
}));

inline constexpr auto BASH_KEYWORDS = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("break"),
    MENDO_LIT("case"),
    MENDO_LIT("continue"),
    MENDO_LIT("declare"),
    MENDO_LIT("do"),
    MENDO_LIT("done"),
    MENDO_LIT("elif"),
    MENDO_LIT("else"),
    MENDO_LIT("esac"),
    MENDO_LIT("eval"),
    MENDO_LIT("exec"),
    MENDO_LIT("exit"),
    MENDO_LIT("export"),
    MENDO_LIT("fi"),
    MENDO_LIT("for"),
    MENDO_LIT("function"),
    MENDO_LIT("if"),
    MENDO_LIT("in"),
    MENDO_LIT("local"),
    MENDO_LIT("readonly"),
    MENDO_LIT("return"),
    MENDO_LIT("select"),
    MENDO_LIT("set"),
    MENDO_LIT("shift"),
    MENDO_LIT("source"),
    MENDO_LIT("then"),
    MENDO_LIT("time"),
    MENDO_LIT("trap"),
    MENDO_LIT("typeset"),
    MENDO_LIT("unset"),
    MENDO_LIT("until"),
    MENDO_LIT("while"),
}));

inline constexpr auto BASH_TYPES = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("alias"),
    MENDO_LIT("builtin"),
    MENDO_LIT("cd"),
    MENDO_LIT("command"),
    MENDO_LIT("echo"),
    MENDO_LIT("false"),
    MENDO_LIT("getopts"),
    MENDO_LIT("let"),
    MENDO_LIT("mapfile"),
    MENDO_LIT("printf"),
    MENDO_LIT("pwd"),
    MENDO_LIT("read"),
    MENDO_LIT("readarray"),
    MENDO_LIT("test"),
    MENDO_LIT("true"),
    MENDO_LIT("type"),
    MENDO_LIT("unalias"),
    MENDO_LIT("which"),
}));

// PowerShell（大文字小文字を区別しないマッチングのためキーワードは小文字で格納）
inline constexpr auto PWSH_KEYWORDS = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("begin"),
    MENDO_LIT("break"),
    MENDO_LIT("catch"),
    MENDO_LIT("class"),
    MENDO_LIT("continue"),
    MENDO_LIT("data"),
    MENDO_LIT("do"),
    MENDO_LIT("dynamicparam"),
    MENDO_LIT("else"),
    MENDO_LIT("elseif"),
    MENDO_LIT("end"),
    MENDO_LIT("enum"),
    MENDO_LIT("exit"),
    MENDO_LIT("filter"),
    MENDO_LIT("finally"),
    MENDO_LIT("for"),
    MENDO_LIT("foreach"),
    MENDO_LIT("from"),
    MENDO_LIT("function"),
    MENDO_LIT("hidden"),
    MENDO_LIT("if"),
    MENDO_LIT("in"),
    MENDO_LIT("inlinescript"),
    MENDO_LIT("param"),
    MENDO_LIT("process"),
    MENDO_LIT("return"),
    MENDO_LIT("static"),
    MENDO_LIT("switch"),
    MENDO_LIT("throw"),
    MENDO_LIT("trap"),
    MENDO_LIT("try"),
    MENDO_LIT("until"),
    MENDO_LIT("using"),
    MENDO_LIT("while"),
    MENDO_LIT("workflow"),
}));

inline constexpr auto PWSH_TYPES = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("array"),
    MENDO_LIT("bool"),
    MENDO_LIT("byte"),
    MENDO_LIT("char"),
    MENDO_LIT("datetime"),
    MENDO_LIT("decimal"),
    MENDO_LIT("double"),
    MENDO_LIT("false"),
    MENDO_LIT("float"),
    MENDO_LIT("hashtable"),
    MENDO_LIT("int"),
    MENDO_LIT("long"),
    MENDO_LIT("null"),
    MENDO_LIT("regex"),
    MENDO_LIT("scriptblock"),
    MENDO_LIT("string"),
    MENDO_LIT("timespan"),
    MENDO_LIT("true"),
    MENDO_LIT("void"),
    MENDO_LIT("xml"),
}));

// Cmd（大文字小文字を区別しないマッチングのためキーワードは小文字で格納）
inline constexpr auto CMD_KEYWORDS = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("call"),
    MENDO_LIT("defined"),
    MENDO_LIT("do"),
    MENDO_LIT("echo"),
    MENDO_LIT("else"),
    MENDO_LIT("endlocal"),
    MENDO_LIT("equ"),
    MENDO_LIT("errorlevel"),
    MENDO_LIT("exist"),
    MENDO_LIT("exit"),
    MENDO_LIT("for"),
    MENDO_LIT("geq"),
    MENDO_LIT("goto"),
    MENDO_LIT("gtr"),
    MENDO_LIT("if"),
    MENDO_LIT("in"),
    MENDO_LIT("leq"),
    MENDO_LIT("lss"),
    MENDO_LIT("neq"),
    MENDO_LIT("not"),
    MENDO_LIT("off"),
    MENDO_LIT("on"),
    MENDO_LIT("pause"),
    MENDO_LIT("rem"),
    MENDO_LIT("set"),
    MENDO_LIT("setlocal"),
}));

inline constexpr auto CMD_TYPES = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("attrib"),
    MENDO_LIT("cls"),
    MENDO_LIT("color"),
    MENDO_LIT("copy"),
    MENDO_LIT("del"),
    MENDO_LIT("dir"),
    MENDO_LIT("find"),
    MENDO_LIT("findstr"),
    MENDO_LIT("ipconfig"),
    MENDO_LIT("md"),
    MENDO_LIT("mkdir"),
    MENDO_LIT("more"),
    MENDO_LIT("move"),
    MENDO_LIT("net"),
    MENDO_LIT("netsh"),
    MENDO_LIT("ping"),
    MENDO_LIT("rd"),
    MENDO_LIT("reg"),
    MENDO_LIT("ren"),
    MENDO_LIT("rename"),
    MENDO_LIT("rmdir"),
    MENDO_LIT("robocopy"),
    MENDO_LIT("sc"),
    MENDO_LIT("sort"),
    MENDO_LIT("start"),
    MENDO_LIT("taskkill"),
    MENDO_LIT("tasklist"),
    MENDO_LIT("title"),
    MENDO_LIT("type"),
    MENDO_LIT("ver"),
    MENDO_LIT("xcopy"),
}));

// JSON / JSONC: リテラル値のみ。型名は該当概念がない。
inline constexpr auto JSON_KEYWORDS = MakeBucketed(std::to_array<mendo::doc_string_view>({
    MENDO_LIT("false"),
    MENDO_LIT("null"),
    MENDO_LIT("true"),
}));

} // namespace syntax_keywords
